/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hedera.account;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        var app = new App();
        var greeting = app.getGreeting();

        System.out.println(greeting);
    }
}
